services:
  app:
    build:
      context: ./../.
      dockerfile: .docker/Dockerfile.dev
      args:
        - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./../:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
